apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: linkding
  namespace: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
#      securityContext:
#        runAsUser: 33
#        runAsGroup: 33
#        fsGroup: 33

      containers:
      - image: sissbruecker/linkding:latest
        name: linkding
        volumeMounts:
           - mountPath: "etc/linkding/linkding-data"
             name: linkding-pvc
        securityContext:
          allowPrivilegeEscalation: false

        ports:
        - containerPort: 9090

      volumes:
        - name: linkding-pvc
          persistentVolumeClaim:
            claimName: linkding-pvc

