apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: linkding
  namespace: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
      - image: sissbruecker/linkding:latest
        name: linkding
      volumes:
        - name: linkding-pvc
          persistentVolumeClaim:
            claimName: linkding-pvc
        ports:
          - containerPort: 9090
