apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pve-exporter
  name: pve-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pve-exporter
  strategy: {}
  template:
    metadata:
      labels:
        app: pve-exporter
    spec:
      containers:
      - image: prompve/prometheus-pve-exporter
        name: prometheus-pve-exporter
        resources: {}
status: {}
